### ISSUE TITLE
project3-srs-submission

### ISSUE THREAD

**Issue by ShiraCahen** [ShiraCahen/Parents-Patrol#2]

**Comment by ShiraCahen** [comment]
https://github.com/ShiraCahen/Parents-Patrol/wiki/SRS

**Comment by oriYedidLevy** [comment]
https://github.com/ShiraCahen/Parents-Patrol/wiki/SRS

**Comment by robi-y** [comment]
- remove issue text
- missing stakeholder
- simplify/refine diagram?
- UC2: generate report
- prototype section
